### ISSUE TITLE
Notepad++ packaged appimage fails to launch

### ISSUE THREAD

**Issue by mmtrt** [sudo-give-me-coffee/wine-appimage#7]
First commands install then I left run npp on setup as checked which executed the app fine then I create package. I'm using locally updated appimage downloaded from here earlier with current changes of 046054a848716df16cc69cb8d0c46c36eef423f2

```
./Wine-x86_64.AppImage install notepadpp ../npp.7.8.3.Installer.exe
ERROR: ld.so: object '/tmp/.mount_Wine-xYPYgYa/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/.mount_Wine-xYPYgYa/bin/libhookexecv.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
0034:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

./notepadpp-x86_64.AppImage 
wine-4.21
wine: configuration in L"/home/mmtrt/.config/notepadpp" has been updated.
Wine cannot find the ncurses library (libncurses.so.5).
```
![npp](https://user-images.githubusercontent.com/2322598/72822557-1bf3a480-3c94-11ea-840d-120f56f0a09e.gif)

**Comment by probonopd** [comment]
Does https://github.com/probonopd/libhookexecv/releases/download/continuous/NotepadPlusPlus-7.7.1-x86_64.AppImage work for you?

This is how it was made:
https://github.com/probonopd/libhookexecv/blob/master/winedeploy.sh

**Comment by mmtrt** [comment]
@probonopd that appimg works fine.

**Comment by sudo-give-me-coffee** [comment]
@probonopd I use (essentially)  the [same way to build](https://github.com/sudo-give-me-coffee/win32-appimage/blob/master/deploy/build.sh) with the main difference is run strip command on all files and folders:

https://github.com/sudo-give-me-coffee/win32-appimage/blob/046054a848716df16cc69cb8d0c46c36eef423f2/data/strip#L231-L235

By removing these lines, Notepad++ works normally for me, but i don't think that is a good thing, because for some reason, by doing doing it, Wine ignores this:

https://github.com/sudo-give-me-coffee/win32-appimage/blob/046054a848716df16cc69cb8d0c46c36eef423f2/data/WineLauncher#L25-L26

And the fonts look very ugly

<hr>


By the way,  these errors is caused by [these lines in Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8fdfc4c2ac9a2f143f0dd4afc2b70bf8b30b1059/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L209-L219), compiling without these lines also works

**Comment by probonopd** [comment]
Maybe the DLL signature verification doesn't like the `strip`, just guessing.

**Comment by sudo-give-me-coffee** [comment]
I will do a complete restructuring, handling better with this and other questions, thanks

**Comment by sudo-give-me-coffee** [comment]
I don't know how this error occurs, but I identified the solution, bundling system.reg makes application runs. I will be add a flag on next commit
